name: Docker

on:
  push:
    branches:
      - master
      - nocomp
    tags:
      - *

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        uses: openzim/docker-publish-action@v9
        with:
          image-name: openzim/sotoki
          on-master: dev
          tag-pattern: /^(.+)$/
          latest-on-tag: false
          restrict-to: openzim/sotoki
          repo_description: auto
          repo_overview: auto
          credentials:
            DOCKERIO_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERIO_TOKEN=${{ secrets.DOCKERHUB_PASSWORD }}
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
